const roadmap=[
 {name:'C Programming Basics',desc:'Build your first mental model of code, variables, and logic.',level:'Start here',video:'C Programming Full Course for Beginners',channel:'freeCodeCamp.org',query:'C programming full course beginners freeCodeCamp'},
 {name:'Python',desc:'Learn a friendly, powerful language for real projects.',level:'Core skill',video:'Python Tutorial for Beginners',channel:'Programming with Mosh',query:'Python tutorial beginners Programming with Mosh'},
 {name:'SQL',desc:'Talk to data and understand what powers every product.',level:'Core skill',video:'SQL Tutorial - Full Database Course',channel:'freeCodeCamp.org',query:'SQL tutorial full course freeCodeCamp'},
 {name:'HTML',desc:'Structure the web with confidence.',level:'Web foundations',video:'HTML Full Course',channel:'Bro Code',query:'HTML full course beginners Bro Code'},
 {name:'CSS',desc:'Turn structure into interfaces people enjoy using.',level:'Web foundations',video:'CSS Tutorial - Full Course for Beginners',channel:'freeCodeCamp.org',query:'CSS full course beginners freeCodeCamp'},
 {name:'JavaScript Basics',desc:'Make your websites respond, think, and feel alive.',level:'Web foundations',video:'JavaScript Full Course for Beginners',channel:'freeCodeCamp.org',query:'JavaScript full course beginners freeCodeCamp'},
 {name:'Flask / Django',desc:'Connect your skills to real backends and APIs.',level:'Build',video:'Python Flask Tutorial for Beginners',channel:'freeCodeCamp.org',query:'Python Flask tutorial beginners freeCodeCamp'},
 {name:'Git & GitHub',desc:'Ship your work and collaborate like a professional.',level:'Workflow',video:'Git and GitHub for Beginners',channel:'Khan Academy',query:'Git GitHub tutorial beginners'},
 {name:'DSA',desc:'Train your problem-solving muscles for interviews.',level:'Interview skill',video:'Data Structures and Algorithms',channel:'freeCodeCamp.org',query:'data structures algorithms full course beginners'},
 {name:'Projects',desc:'Turn knowledge into proof with a portfolio you own.',level:'Portfolio',video:'How to Build Projects as a Beginner',channel:'Ali Abdaal',query:'coding projects beginners portfolio'},
 {name:'AI Integration',desc:'Add useful AI features to the things you build.',level:'Future skill',video:'Build AI Apps with Python',channel:'freeCodeCamp.org',query:'build AI apps Python beginners'},
 {name:'Internship Preparation',desc:'Get your profile ready for your first opportunity.',level:'Career',video:'How to Get a Coding Internship',channel:'NeetCode',query:'how to get coding internship beginner'},
 {name:'Job Preparation',desc:'Practice the skills and stories interviews look for.',level:'Career',video:'Coding Interview Preparation',channel:'NeetCode',query:'coding interview preparation beginners'},
 {name:'Work Experience',desc:'Grow through feedback, teamwork, and shipping.',level:'Growth',video:'How to Work as a Junior Developer',channel:'Fireship',query:'junior developer career advice'},
 {name:'B.Tech / Further Skill Growth',desc:'Choose your next edge and keep moving forward.',level:'Long game',video:'How to Keep Learning as a Developer',channel:'Fireship',query:'developer continuous learning skills'}
];
const defaultState={name:'Student',completed:[],savedVideos:[],savedNotes:[],quizScores:{},projects:{},theme:'dark',onboarded:false,streak:4};
let state={...defaultState,...JSON.parse(localStorage.getItem('futureState')||'{}')};
let currentView='home'; let selectedTopic=state.completed.length<roadmap.length?state.completed.length:roadmap.length-1;
const app=document.getElementById('app');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function save(){localStorage.setItem('futureState',JSON.stringify(state));}
function toast(message){const t=document.getElementById('toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function progress(){return Math.round(state.completed.length/roadmap.length*100)}
function colure(){const messages=['Yo! Ready to level up your coding skills?','Small progress every day becomes a big career.','Don’t stress about mistakes. That’s how developers grow.','Your next move is '+roadmap[selectedTopic].name+'. Let’s get it!'];return `<div class="colure"><strong>Colure says</strong><br>${messages[state.completed.length%messages.length]}</div>`}
function layout(content,title){document.getElementById('breadcrumb').textContent=`Future / ${title}`;app.innerHTML=`<section class="view">${content}</section>`;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{currentView=b.dataset.view;render()});document.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>{if(b.dataset.locked==='true'){toast('Complete the previous topic to unlock this step.');return}selectedTopic=Number(b.dataset.topic);currentView='learn';render()});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>actions(b.dataset.action,b));document.querySelectorAll('[data-project]').forEach(b=>b.onchange=()=>{state.projects[b.dataset.project]=b.checked;save();toast(b.checked?'Milestone saved.':'Milestone unchecked.');});}
function home(){const next=roadmap[selectedTopic];return `<div class="hero"><div><div class="eyebrow">YOUR CAREER, ONE STEP AT A TIME</div><h1>Welcome to Future, ${esc(state.name)}.</h1><p>A clear path from your first line of code to your first opportunity.</p></div>${colure()}</div><div class="grid stats-grid"><div class="card"><div class="stat-label">Overall progress</div><div class="stat-value">${progress()}<span>%</span></div><div class="progress-track"><div class="progress-fill" style="width:${progress()}%"></div></div></div><div class="card"><div class="stat-label">Learning streak</div><div class="stat-value">${state.streak}<span> days</span></div><p class="stat-label">Keep the rhythm going.</p></div><div class="card"><div class="stat-label">Topics completed</div><div class="stat-value">${state.completed.length}<span> / ${roadmap.length}</span></div></div><div class="card"><div class="stat-label">Quiz scores</div><div class="stat-value">${Object.keys(state.quizScores).length}<span> taken</span></div></div></div><div class="grid two-col"><div class="card next-card"><div><span class="tag">YOUR NEXT MOVE</span><h2>${next.name}</h2><p>${next.desc}</p></div><div class="button-row"><button class="primary-button" data-action="continue">Continue learning <span>→</span></button><button class="secondary-button" data-view="roadmap">View roadmap</button></div></div><div class="card"><div class="section-title"><h3>Recent activity</h3><button class="text-button" data-view="profile">See all</button></div><div class="activity-list">${state.completed.length?state.completed.slice(-3).reverse().map(i=>`<div class="activity"><div class="activity-icon">✓</div><div>Completed ${roadmap[i].name}<small>Nice work, keep going.</small></div></div>`).join(''):`<div class="empty">Your first completed topic will show up here.</div>`}</div></div></div>`}
function roadmapView(){return `<div class="hero"><div><div class="eyebrow">THE FULL PATH</div><h1>Your roadmap.</h1><p>Follow the sequence, build the habit, and unlock your next chapter.</p></div>${colure()}</div><div class="roadmap">${roadmap.map((t,i)=>{const done=state.completed.includes(i);const locked=i>0&&!state.completed.includes(i-1)&&!done;return `<div class="roadmap-item ${done?'done':''} ${locked?'locked':''}" data-topic="${i}" data-locked="${locked}"><div class="roadmap-number">${done?'✓':locked?'🔒':String(i+1).padStart(2,'0')}</div><div><h3>${t.name}</h3><p>${t.desc}</p></div><div class="status">${done?'Completed':locked?'Locked':'Start learning →'}</div></div>`}).join('')}</div>`}
function learnView(){const t=roadmap[selectedTopic];const done=state.completed.includes(selectedTopic);return `<div class="topic-header"><div><div class="eyebrow">STEP ${String(selectedTopic+1).padStart(2,'0')} / ${roadmap.length} · ${t.level.toUpperCase()}</div><h1>${t.name}</h1><p>${t.desc} Start with one focused session, then test what stuck.</p></div>${colure()}</div><div class="grid resource-grid"><div class="card resource-card"><span class="tag">WATCH</span><h3>${t.video}</h3><p>${t.channel} · Beginner friendly</p><button class="primary-button" data-action="video">Open on YouTube ↗</button></div><div class="card resource-card"><span class="tag">NOTES</span><h3>Easy notes for ${t.name}</h3><p>Learn the core idea, see a tiny example, and keep a quick revision summary.</p><button class="secondary-button" data-action="notes">Read notes</button></div><div class="card resource-card"><span class="tag">PRACTICE</span><h3>Check your understanding</h3><p>One quick question with instant feedback. No pressure, just reps.</p><button class="secondary-button" data-action="quiz">Take quiz</button></div></div><div class="card" style="margin-top:18px"><div class="section-title"><h3>Topic progress</h3><span class="status">${done?'Completed':'In progress'}</span></div><div class="progress-track"><div class="progress-fill" style="width:${done?100:35}%"></div></div><div class="button-row" style="margin-top:18px"><button class="primary-button" data-action="complete">${done?'Completed ✓':'Mark topic complete'}</button>${selectedTopic<roadmap.length-1?'<button class="secondary-button" data-action="next">Next topic →</button>':''}</div></div>`}
function videosView(){const query=document.getElementById('videoSearch')?.value||'';const list=roadmap.filter(t=>`${t.name} ${t.video} ${t.channel}`.toLowerCase().includes(query.toLowerCase()));return `<div class="hero"><div><div class="eyebrow">CURATED FOR BEGINNERS</div><h1>Best videos.</h1><p>Open a focused lesson from a creator who explains the why, not just the syntax.</p></div>${colure()}</div><div class="filter-row"><input class="search" id="videoSearch" placeholder="Search topics or creators..." value="${esc(query)}"></div><div class="grid">${list.map(t=>{const index=roadmap.indexOf(t);return `<div class="card video-card"><div class="video-thumb">▶</div><div class="video-info"><h3>${t.video}</h3><p>${t.channel} · ${t.name}</p></div><button class="save-button ${state.savedVideos.includes(index)?'saved':''}" data-action="save-video" data-index="${index}" title="Save video">♡</button><button class="secondary-button" data-action="video" data-index="${index}">Open</button></div>`}).join('')||'<div class="card empty">Colure couldn’t find that yet. Try a topic like Python or SQL.</div>'}</div>`}
function notesView(){const t=roadmap[selectedTopic];return `<div class="topic-header"><div><div class="eyebrow">QUICK REVISION</div><h1>${t.name} notes.</h1><p>Simple explanations you can come back to whenever you need a reset.</p></div>${colure()}</div><div class="grid two-col"><div class="card"><h3>The big idea</h3><p>${t.desc} Think of this topic as a tool in your developer toolkit. Learn one concept, use it in a tiny example, then explain it in your own words.</p><h3>Try this</h3><div class="code">// your practice prompt<br>const nextStep = "learn, build, repeat";<br>console.log(nextStep);</div><h3>Common mistake</h3><p>Trying to memorize everything before making anything. Keep the feedback loop short.</p></div><div class="card"><h3>Quick revision</h3><div class="checklist"><label><input type="checkbox"> I can explain the core idea</label><label><input type="checkbox"> I can recognize the basic syntax</label><label><input type="checkbox"> I can solve one tiny problem</label><label><input type="checkbox"> I can teach this to a friend</label></div><button class="primary-button" style="margin-top:20px" data-action="save-note">Save these notes</button></div></div>`}
function practiceView(){const t=roadmap[selectedTopic];const score=state.quizScores[selectedTopic];return `<div class="hero"><div><div class="eyebrow">PRACTICE LAB</div><h1>Practice ${t.name}.</h1><p>Knowledge becomes a skill when you use it. Start small and let the reps stack up.</p></div>${colure()}</div><div class="card"><div class="section-title"><h3>Quick check</h3>${score!==undefined?`<span class="tag">Last score: ${score}/1</span>`:''}</div><p><strong>What is the best way to learn ${t.name}?</strong></p><div class="button-row"><button class="secondary-button" data-action="answer" data-answer="wrong">Read everything first</button><button class="secondary-button" data-action="answer" data-answer="right">Learn one idea, then practice it</button><button class="secondary-button" data-action="answer" data-answer="wrong">Skip straight to interviews</button></div></div>`}
function projectsView(){const projects=[['Personal portfolio','Beginner','HTML · CSS · GitHub'],['Task tracker API','Intermediate','Python · Flask · SQL'],['AI study buddy','Advanced','Python · APIs · AI']];return `<div class="hero"><div><div class="eyebrow">BUILD YOUR PROOF</div><h1>Projects that tell your story.</h1><p>Start small, ship often, and document what you learned along the way.</p></div>${colure()}</div><div class="grid project-grid">${projects.map((p,i)=>`<div class="card project-card"><span class="tag">${p[1]}</span><h3>${p[0]}</h3><p>${p[2]}</p><div class="checklist"><label><input type="checkbox" ${state.projects[i]?'checked':''} data-project="${i}"> First milestone complete</label></div><button class="secondary-button" style="margin-top:15px" data-action="project" data-index="${i}">View brief</button></div>`).join('')}</div>`}
function jobsView(){return `<div class="hero"><div><div class="eyebrow">FROM LEARNING TO OPPORTUNITY</div><h1>Job preparation.</h1><p>Preparation helps. Employment depends on your skills, applications, interviews, and the market.</p></div>${colure()}</div><div class="job-list">${[['Resume basics','Make your projects easy to scan: action, tech, outcome.'],['GitHub profile','Pin two or three projects and write useful READMEs.'],['LinkedIn basics','Use a clear headline and share what you are learning.'],['Interview practice','Tell the story of a bug, a tradeoff, and a win.'],['Python interview questions','Review data types, functions, OOP, and debugging.'],['SQL interview questions','Practice joins, grouping, filtering, and schema thinking.'],['Internship preparation','Apply consistently and ask for specific feedback.'],['Application tracker','Track role, date, follow-up, and what you learned.']].map(j=>`<div class="job-item"><h3>${j[0]}</h3><p>${j[1]}</p></div>`).join('')}</div>`}
function profileView(){const savedVideos=state.savedVideos.map(i=>roadmap[i]).filter(Boolean);const savedNotes=state.savedNotes.map(i=>roadmap[i]).filter(Boolean);return `<div class="hero"><div><div class="eyebrow">YOUR SPACE</div><h1>${esc(state.name)}’s profile.</h1><p>Keep your preferences and progress in one place.</p></div>${colure()}</div><div class="grid two-col"><div class="card"><h3>Journey summary</h3><div class="progress-meta"><span>Roadmap progress</span><span>${progress()}%</span></div><div class="progress-track"><div class="progress-fill" style="width:${progress()}%"></div></div><p class="stat-label" style="margin-top:18px">${state.completed.length} topics completed · ${state.savedVideos.length} videos saved · ${state.savedNotes.length} notes saved</p><h3 style="margin-top:24px">Saved content</h3><p class="stat-label">${savedVideos.length?savedVideos.map(t=>`▶ ${t.name}`).join('<br>'):'No saved videos yet.'}</p><p class="stat-label">${savedNotes.length?savedNotes.map(t=>`≡ ${t.name}`).join('<br>'):'No saved notes yet.'}</p></div><div class="card"><h3>Preferences</h3><div class="button-row" style="margin-top:16px"><button class="secondary-button" data-action="onboarding">Edit profile</button><button class="secondary-button" data-action="reset">Reset demo data</button></div><p class="brand-credit" style="margin:24px 0 0">Future<br>Built by Shubham Rao</p></div></div>`}
function render(){document.body.classList.toggle('light',state.theme==='light');document.getElementById('topUser').textContent=state.name;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===currentView));const views={home:['Dashboard',home],roadmap:['Roadmap',roadmapView],learn:['Learn',learnView],videos:['Best Videos',videosView],notes:['Notes',notesView],practice:['Practice',practiceView],projects:['Projects',projectsView],jobs:['Job Preparation',jobsView],profile:['Profile',profileView]};layout(views[currentView][1](),views[currentView][0]);if(currentView==='videos'){document.getElementById('videoSearch').oninput=()=>render()}}
function actions(action,element){const index=Number(element?.dataset?.index);if(action==='continue'||action==='next'){selectedTopic=Math.min(selectedTopic+1,roadmap.length-1);currentView='learn';render()}else if(action==='complete'){if(!state.completed.includes(selectedTopic))state.completed.push(selectedTopic);save();toast('Nice work! Topic completed.');render()}else if(action==='video'){const t=roadmap[Number.isNaN(index)?selectedTopic:index];window.open('https://www.youtube.com/results?search_query='+encodeURIComponent(t.query),'_blank','noopener');toast('Opening a focused YouTube search.')}else if(action==='save-video'){if(!state.savedVideos.includes(index))state.savedVideos.push(index);else state.savedVideos=state.savedVideos.filter(i=>i!==index);save();render()}else if(action==='save-note'){if(!state.savedNotes.includes(selectedTopic))state.savedNotes.push(selectedTopic);save();toast('Notes saved for later.')}else if(action==='notes'){currentView='notes';render()}else if(action==='quiz'){currentView='practice';render()}else if(action==='answer'){state.quizScores[selectedTopic]=element.dataset.answer==='right'?1:0;save();toast(element.dataset.answer==='right'?'Correct. You’re building the habit.':'Not quite. Read the notes and try again.');render()}else if(action==='onboarding'){document.getElementById('onboardingModal').classList.remove('hidden')}else if(action==='reset'){localStorage.removeItem('futureState');location.reload()}else if(action==='project'){toast('Project brief unlocked. Start with the first milestone.')}}
document.getElementById('themeToggle').onclick=()=>{state.theme=state.theme==='light'?'dark':'light';save();render()};document.getElementById('mobileMenu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');document.getElementById('closeOnboarding').onclick=()=>document.getElementById('onboardingModal').classList.add('hidden');document.getElementById('onboardingForm').onsubmit=e=>{e.preventDefault();const data=new FormData(e.target);state.name=data.get('name');state.onboarded=true;save();document.getElementById('onboardingModal').classList.add('hidden');toast(`Welcome, ${state.name}. Your journey starts now.`);render()};document.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b&&b.closest('.profile-chip,.button-row,.section-title')){currentView=b.dataset.view;render()}const a=e.target.closest('[data-action]');if(a)window.event=e});
if(!state.onboarded)setTimeout(()=>document.getElementById('onboardingModal').classList.remove('hidden'),500);render();